# Generated by Django 5.2.1 on 2025-08-30 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_llegada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('numero_personas', models.PositiveIntegerField()),
                ('tipo_plan', models.CharField(choices=[('basico', 'Básico'), ('premium', 'Premium'), ('vip', 'VIP')], max_length=20)),
            ],
        ),
    ]
